import { createWorker } from 'tesseract.js';
import PizZipCallback from 'pizzip';
import DocxtemplaterCallback from 'docxtemplater';

const PizZip = (typeof PizZipCallback === 'function' ? PizZipCallback : (PizZipCallback as any).default || PizZipCallback) as any;
const Docxtemplater = (typeof DocxtemplaterCallback === 'function' ? DocxtemplaterCallback : (DocxtemplaterCallback as any).default || DocxtemplaterCallback) as any;

export interface ExtractionResult {
  text: string;
}

export const apiService = {
  async extractText(file: File, onProgress?: (message: string) => void): Promise<ExtractionResult> {
    try {
      console.log('Iniciando OCR para arquivo:', file.name, file.type, file.size);
      if (onProgress) onProgress('Preparando imagem...');

      // 1. Create a canvas to preprocess the image
      const image = await new Promise<HTMLImageElement>((resolve, reject) => {
        const img = new Image();
        img.onload = () => resolve(img);
        img.onerror = (e) => reject(new Error('Erro ao carregar imagem: ' + e));
        img.src = URL.createObjectURL(file);
      });

      console.log('Imagem carregada:', image.width, 'x', image.height);

      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      if (!ctx) throw new Error('Canvas context could not be created');

      // Downscale if image is too large (max 1600px width/height)
      const MAX_DIM = 1600;
      let width = image.width;
      let height = image.height;
      
      if (width > MAX_DIM || height > MAX_DIM) {
        if (width > height) {
          height *= MAX_DIM / width;
          width = MAX_DIM;
        } else {
          width *= MAX_DIM / height;
          height = MAX_DIM;
        }
        console.log('Redimensionando para:', Math.round(width), 'x', Math.round(height));
      }

      canvas.width = width;
      canvas.height = height;

      // Draw original image scaled
      ctx.drawImage(image, 0, 0, width, height);

      // Preprocessing: Simple grayscale transformation
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const data = imageData.data;
      
      for (let i = 0; i < data.length; i += 4) {
        // Grayscale conversion using luminosity weights
        const gray = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
        data[i] = data[i + 1] = data[i + 2] = gray;
      }
      ctx.putImageData(imageData, 0, 0);

      // Convert canvas to blob for Tesseract
      const processedBlob = await new Promise<Blob>((resolve, reject) => {
        canvas.toBlob((blob) => {
          if (blob) resolve(blob);
          else reject(new Error('Failed to create blob from canvas'));
        }, 'image/jpeg', 0.9);
      });

      URL.revokeObjectURL(image.src);
      console.log('Pre-processamento concluído');

      // 2. Perform OCR on the processed image
      const worker = await createWorker('por', 1, {
        logger: m => {
          console.log('Tesseract:', m);
          if (onProgress && typeof m === 'object' && m !== null) {
            if (m.status === 'recognizing text') {
              onProgress(`Reconhecendo: ${Math.round(m.progress * 100)}%`);
            } else {
              onProgress(`${m.status}`);
            }
          }
        }
      });
      
      console.log('Worker pronto');
      const { data: { text: rawText } } = await worker.recognize(processedBlob);
      console.log('Reconhecimento concluído, tamanho do texto:', rawText?.length);
      
      await worker.terminate();

      if (!rawText || rawText.trim().length === 0) {
        console.warn('OCR retornou texto vazio');
        throw new Error('Não foi possível extrair texto da imagem. Tente uma foto mais nítida.');
      }

      return { text: rawText };
    } catch (error) {
      console.error('Client-side OCR Error:', error);
      throw new Error(error instanceof Error ? error.message : 'Falha ao processar o OCR da imagem localmente.');
    }
  },

  async exportToWord(structured: any, title: string = 'PARECER DO CONTROLE INTERNO MUNICIPAL'): Promise<Blob> {
    try {
      // Fetch the template from the dynamic URL generated by Vite
      // Appending a timestamp to bypass service worker/browser aggressive caching
      const response = await fetch('/template.docx?t=' + Date.now());
      if (!response.ok) {
        throw new Error(`Servidor retornou erro ${response.status} ao buscar o template.docx.`);
      }
      
      const contentType = response.headers.get('content-type');
      if (contentType && contentType.includes('text/html')) {
          throw new Error('Recebeu HTML em vez do arquivo DOCX. Configurar regras de redirecionamento corretamente.');
      }

      const arrayBuffer = await response.arrayBuffer();
      
      if (!arrayBuffer || arrayBuffer.byteLength === 0) {
        throw new Error('Template baixado está vazio ou corrompido.');
      }

      // Use PizZip to handle the binary content
      const zip = new PizZip(arrayBuffer);
      const doc = new Docxtemplater(zip, {
        paragraphLoop: true,
        linebreaks: true,
      });

      doc.render({
        ...structured,
        title: title || 'PARECER DO CONTROLE INTERNO MUNICIPAL',
      });

      const out = doc.getZip().generate({
        type: 'blob',
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      });

      return out;
    } catch (error) {
      console.error('Client-side Export Error:', error);
      throw new Error(error instanceof Error ? error.message : 'Falha ao gerar o arquivo Word localmente.');
    }
  },
};
